# Generated by Django 5.1a1 on 2024-05-25 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('items', '0005_remove_itemimage_inventory_item_inventoryitem_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('images', models.ManyToManyField(to='items.itemimage')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.inventoryitem')),
            ],
        ),
    ]
