# Generated by Django 5.1a1 on 2024-05-25 05:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riffraffuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
