# Generated by Django 5.1a1 on 2024-05-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_alter_riffraffuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riffraffuser',
            name='user_type',
            field=models.CharField(
                choices=[('system', 'System'), ('admin', 'Admin'), ('vendor', 'Vendor'), ('buyer', 'Buyer')],
                max_length=6, verbose_name='user type'),
        ),
    ]
