# Generated by Django 5.1a1 on 2024-05-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='inventory_item_images',
                                         to='items.itemimage'),
        ),
    ]
