# Generated by Django 5.1a1 on 2024-05-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('items', '0002_itemimage_inventoryitem_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='images',
            field=models.ManyToManyField(to='items.itemimage'),
        ),
    ]
