# Generated by Django 5.1a1 on 2024-05-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('items', '0004_remove_inventoryitem_images_itemimage_inventory_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='inventory_item',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='images',
            field=models.ManyToManyField(to='items.itemimage'),
        ),
    ]
