# Generated by Django 5.0.6 on 2024-05-27 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_delete_itemimage_alter_inventoryitem_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name': 'Inventory Item'},
        ),
    ]
