# Generated by Django 5.0.6 on 2024-05-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Item Image'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Item Image Name'),
        ),
    ]
